baseURL = "https://example.com"
languageCode = "en-us"
title = "Marco Sciaini"
theme = "cactus"
copyright = "Marco Sciaini" # cactus will use title if copyright is not set
disqusShortname = "example" # Used when comments is enabled. Cactus will use site title if not set
# googleAnalytics = "UA-1234-5"


# summaryLength = 2

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Writings"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3


[markup]
  [markup.tableOfContents]
    endLevel = 4
    ordered = false
    startLevel = 2

[params]

  colortheme = "light" # dark, light, white, or classic
  rss = true # generate rss feed. default value is false
  googleAnalyticsAsync = false # use asynchronous tracking. Synchronous tracking by default

  # Home page settings
  description = "Hi there, I'm Marco. Nice to meet you! I am a Data Analyst and Geospatial Enthusiast. I build custom statistical models, data visualisations, maps and dashboards. Check out my toolbox, thoughts and projects below!"
  mainSection = "posts" # your main section
  showAllPostsOnHomePage = false # default
  postsOnHomePage = 5 # this option will be ignored if showAllPostsOnHomePage is set to true
  tagsOverview = false # show tags overview by default.
  showProjectsList = true # show projects list by default (if projects data file exists).
  projectsUrl = "https://marcosci.github.io" # title link for projects list

  # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
  dateFormat = "2006-01-02" # default

  # Post page settings
  show_updated = false # default

  [params.comments]
    enabled = false # default
    engine = "disqus" # more supported engines will be added.

  # the value of name should be an valid font awesome icon name (brands type)
  # https://fontawesome.com/icons?d=gallery&s=brands
  [[params.social]]
    name = "github"
    link = "https://github.com/marcosci"
  [[params.social]]
    name = "linkedin"
    link = "https://www.linkedin.com/in/marco-sciaini-4735781b8/"
  [[params.social]]
    name = "email"
    link = "marco.sciaini@indblik.io"  # no need for "mailto:" in the head
